name: Build and Deploy to Heroku

on:
  push:
    branches: [ SCRUM-52-deploy-the-app-docker-to-heroku ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          procfile: "web: java -jar target/E-CommerceManagement-0.0-1-SNAPSHOT.jar"
        env:
          SPRING_PROFILES_ACTIVE: h2








